[package]
name = "keri-witness-http"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keri = { git = "https://github.com/decentralized-identity/keriox", rev = "77b5782"}
tokio = { version = "1", features = ["full"] }
warp = "0.3"
ed25519-dalek = "1.0.1"
rand = { version = "0.7.3", features = ["std", "getrandom"] }

[dev-dependencies]
reqwest = "0.11.6"